### ISSUE TITLE
Disable ANSI colors on non supported consoles

### ISSUE THREAD

**Issue by kasvith** [fuelen/ecto_dev_logger#12]
Would it be possible to disable ANSI colours on consoles which it's not supported? For example `iex --werl` on windows doesn't support ANSI colors

An option to disable this would be much more valuable

**Comment by fuelen** [comment]
Hi @kasvith 

Thanks for pointing to this issue. I've fixed it and published a new release. Please check it out

**Comment by kasvith** [comment]
thank you
