### ISSUE TITLE
Support Geo entities

### ISSUE THREAD

**Issue by tcitworld** [fuelen/ecto_dev_logger#22]
The [`geo_postgis`](https://github.com/bryanjos/geo_postgis) Postgrex extension allows entities from the [`geo`](https://github.com/bryanjos/geo) library to be used as PostGIS data types.

It would be nice if the `Ecto.DevLogger.PrintableParameter` protocol supported that. Will see if I can add this easily.

**Comment by iloveitaly** [comment]
@tcitworld were you able to figure this out?

**Comment by tcitworld** [comment]
I forgot! Thanks for opening a PR!
