### ISSUE TITLE
Ecto.Adapters.MySQL uses different param placeholder

### ISSUE THREAD

**Issue by sh41** [fuelen/ecto_dev_logger#8]
Just a note for anyone who like me was trying to figure out why this wasn't working on a MySQL project. MySQL's placeholder is `?` rather than `$1` etc. As a result the DevLogger doesn't replace the right things. I may have a look at a PR for this is I have time, but for the moment hopefully this saves others time when trying to figure out what's happening. 

Great project by the way! I'm looking forward to using it on a Postgres codebase. :D

**Comment by fuelen** [comment]
Hey @sh41 

I've pushed a commit with support for `Ecto.Adapters.MyXQL` adapter to `main`. Could you test it? :)

**Comment by sh41** [comment]
Thanks @fuelen! Looks great! 

![image](https://user-images.githubusercontent.com/6237786/175479103-81af095d-b579-404e-8e77-0e2e72d16a26.png)

It's highlighted something a little odd with some of the strings we're using, but I'll raise another issue for that as it's unrelated to the adapter used.

**Comment by fuelen** [comment]
Released in `v0.3.0`

**Comment by sh41** [comment]
❤️ 💚 💛 🧡
